services:
  web:
    build: .
    ports:
      - "8000:8000"  # Match Uvicorn's default port
    volumes:
      - ./app:/app/app
    environment:
      - DATABASE_URL=sqlite:///./test.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  # Updated Uvicorn command
